### ISSUE TITLE
Kernel panic if httpproxy on

### ISSUE THREAD

**Issue by atocharnaud** [dbnomics-stata/dbnomics#2]
Bonjour,

It seems the dbnomics ado file does not support http proxy for me in the OECD network.

```
. set httpproxy off
(set httpproxy preference recorded)

. dbnomics providers
Downloading list of providers...
r(677);

. set httpproxy on
(set httpproxy preference recorded)

. dbnomics providers
Downloading list of providers...
**Kernel panic. Abort
r(5100);**

```

Our httpproxy is the following:
```
set httpproxyhost "wsg-proxy.oecd.org"
set httpproxyport 80

```

```
. which dbnomics
V:/Users/Atoch_A/BACKUP/ado/plus\d\dbnomics.ado
*! Ver 1.1.1 21oct2018 Simone Signore
*! Stata API client for db.nomics.world. Requires libjson and moss
```

```
//AS-GEN-1/Stata/ado/site\m\moss.ado
*! 2.0.0 29apr2016 Robert Picard
*! 1.1.2 27mar2011 NJC
*! 1.1.1 25mar2011 NJC
*! 1.1.0 20mar2011 Robert Picard
```

Libjson :  Distribution-Date: 20140906

We are running Stata 15.1 (July 2019) x64 on Windows 10

Arnaud

**Comment by dbnomics-stata** [comment]
Hi @atocharnaud,

Really sorry it took me so long to respond. I often face the same issue, but it does not seem to be related to the dbnomics command itself, but rather caused by an issue with https certificates. I tried to explain more in depth here: https://forum.db.nomics.world/t/about-the-stata-plugin/126/23.

In any case, the new release of the command (v1.2.0) not only upgrades the command to the latest API specifications of the DB.nomics platform, but also allows the option **insecure** to issue standard http calls instead of the default https.

Hope this helps, thanks a lot for reporting the issue.
